repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml

  - repo: local
    hooks:
      - id: lint-py
        name: lint-py
        entry: make lint-py
        language: system
        pass_filenames: false
      - id: format-py-check
        name: format-py-check
        entry: make format-py-check
        language: system
        pass_filenames: false
      - id: typecheck-py
        name: typecheck-py
        entry: make typecheck-py
        language: system
        pass_filenames: false
      - id: eslint
        name: eslint
        entry: make lint-js
        language: system
        pass_filenames: false
      - id: prettier-check
        name: prettier-check
        entry: make format-js-check
        language: system
        pass_filenames: false
      - id: web-typecheck
        name: web-typecheck
        entry: make typecheck-web
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: make test-py
        language: system
        pass_filenames: false
      - id: node-test
        name: node-test
        entry: make test-js
        language: system
        pass_filenames: false
