"""Cross-runtime parity tests between Python and web cleaner contracts.

Two layers guard parity. The hand-written ``*-parity.csv`` fixtures pin exact
expected values for readable, targeted cases. The seeded ``*-corpus.csv``
fixtures (generated by ``make gen-parity-corpus``) drive a few hundred rows per
type through both cleaners and assert both match one checked-in expected file
(``parity-corpus-expected.json``, produced by the web cleaner). A cleaning
change in only one runtime then fails ``make test``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

import pandas as pd
import pytest

from linkedin_analyzer.cleaners.comments import clean_comments
from linkedin_analyzer.cleaners.connections import clean_connections
from linkedin_analyzer.cleaners.messages import clean_messages
from linkedin_analyzer.cleaners.shares import clean_shares

if TYPE_CHECKING:
    from collections.abc import Callable

    from linkedin_analyzer.core.types import CleanerResult

FIXTURES_DIR = Path(__file__).parent / "fixtures"
# Cleaned dates are converted from UTC to the local timezone, so parity tests
# assert the format instead of an exact machine-dependent value.
LOCAL_DATETIME_PATTERN = r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$"

CORPUS_CLEANERS: dict[str, Callable[..., CleanerResult]] = {
    "shares": clean_shares,
    "comments": clean_comments,
    "messages": clean_messages,
    "connections": clean_connections,
}


def test_shares_fixture_matches_expected_python_contract(tmp_path: Path) -> None:
    """Shares cleaner should produce stable output for shared parity fixture."""
    output_file = tmp_path / "Shares.xlsx"

    result = clean_shares(
        input_path=FIXTURES_DIR / "shares-parity.csv",
        output_path=output_file,
    )

    assert result.success is True
    df = pd.read_excel(output_file).fillna("")
    assert df["Date"].str.match(LOCAL_DATETIME_PATTERN).all()
    # The impossible date passes through as raw text, which also matches the
    # pattern above, so pin the exact cell explicitly.
    assert df["Date"].iloc[3] == "2026-02-30 10:00:00"
    assert list(df["ShareLink"]) == [
        "https://www.linkedin.com/feed/update/urn:li:share:1",
        "https://www.linkedin.com/feed/update/urn:li:share:2",
        "https://www.linkedin.com/feed/update/urn:li:share:4",
        "https://www.linkedin.com/feed/update/urn:li:share:5",
        "https://www.linkedin.com/feed/update/urn:li:share:6",
    ]
    assert list(df["ShareCommentary"]) == [
        'He said "hi".\n\nNext "line" here.',
        "Smart “quotes” and naïve emoji 📌 stay intact.",
        "'=SUM(A1:B2)",
        "'@mention leads this",
        # The BEL control character (\x07) is stripped so the export stays writable.
        "Bellchar removed",
    ]
    assert list(df["SharedUrl"]) == ["https://example.com/post", "", "", "", ""]
    assert list(df["MediaUrl"]) == ["", "", "", "", ""]
    assert list(df["Visibility"]) == [
        "MEMBER_NETWORK",
        "CONNECTIONS",
        "MEMBER_NETWORK",
        "CONNECTIONS",
        "MEMBER_NETWORK",
    ]


def test_comments_fixture_matches_expected_python_contract(tmp_path: Path) -> None:
    """Comments cleaner should produce stable output for shared parity fixture."""
    output_file = tmp_path / "Comments.xlsx"

    result = clean_comments(
        input_path=FIXTURES_DIR / "comments-parity.csv",
        output_path=output_file,
    )

    assert result.success is True
    df = pd.read_excel(output_file).fillna("")
    # The "none" row is dropped (Message required, NONE is a sentinel).
    assert len(df) == 3
    assert df["Date"].str.match(LOCAL_DATETIME_PATTERN).all()
    assert list(df["Link"]) == [
        "https://www.linkedin.com/feed/update/urn:li:activity:1",
        "https://www.linkedin.com/feed/update/urn:li:activity:2",
        "https://www.linkedin.com/feed/update/urn:li:activity:4",
    ]
    assert list(df["Message"]) == [
        'She wrote "great post" yesterday.\n📌 Naïve “smart quotes” line.',
        'Plain text with "doubled" quotes',
        "'+1 first-token payload",
    ]


def test_messages_fixture_matches_expected_python_contract(tmp_path: Path) -> None:
    """Messages cleaner should produce stable output for shared parity fixture."""
    output_file = tmp_path / "Messages.xlsx"

    result = clean_messages(
        input_path=FIXTURES_DIR / "messages-parity.csv",
        output_path=output_file,
    )

    assert result.success is True
    df = pd.read_excel(output_file).fillna("")
    assert list(df["FROM"]) == ["Ada", "Eve"]
    assert list(df["TO"]) == ["Bob", "Bob"]
    assert df["DATE"].str.match(LOCAL_DATETIME_PATTERN).all()
    # UTC is stripped, then the impossible date passes through as raw text,
    # which also matches the pattern above, so pin the exact cell explicitly.
    assert df["DATE"].iloc[1] == "2026-02-30 10:00:00"
    assert list(df["CONTENT"]) == ['He said "hello"', "'-2 plus 2"]
    assert list(df["FOLDER"]) == ["INBOX", "ARCHIVE"]
    assert list(df["CONVERSATION ID"]) == ["abc", "ghi"]
    assert list(df["SENDER PROFILE URL"]) == ["https://linkedin.com/in/ada", ""]
    assert list(df["RECIPIENT PROFILE URLS"]) == ["https://linkedin.com/in/bob", ""]


def test_connections_fixture_matches_expected_python_contract(tmp_path: Path) -> None:
    """Connections cleaner should produce stable output for shared parity fixture."""
    output_file = tmp_path / "Connections.xlsx"

    result = clean_connections(
        input_path=FIXTURES_DIR / "connections-parity.csv",
        output_path=output_file,
    )

    assert result.success is True
    df = pd.read_excel(output_file).fillna("")
    assert list(df["First Name"]) == ["Ada", "", "'=2+5", "Bob"]
    assert list(df["Last Name"]) == ["Lovelace", "Builder", "'+Lovelace", "Builder II"]
    assert list(df["URL"]) == [
        "https://linkedin.com/in/ada",
        "https://linkedin.com/in/bob",
        "",
        "https://linkedin.com/in/bob2",
    ]
    assert list(df["Email Address"]) == ["", "", "", ""]
    assert list(df["Company"]) == [
        "Analytical Engines",
        "Builders Inc",
        "'-Analytical Co",
        "Builders Inc",
    ]
    assert list(df["Position"]) == ["Mathematician", "Engineer", "'@Handle Corp", "Engineer"]
    # The impossible "30 Feb 2026" date passes through as raw text.
    assert list(df["Connected On"]) == ["2026-01-30", "2026-02-15", "30 Feb 2026", "2026-09-15"]


@pytest.mark.parametrize("file_type", ["shares", "comments", "messages", "connections"])
def test_synthetic_corpus_matches_web_cleaner(file_type: str, tmp_path: Path) -> None:
    """Python cleaner output must equal the web cleaner's for the shared corpus."""
    expected = json.loads(
        (FIXTURES_DIR / "parity-corpus-expected.json").read_text(encoding="utf-8"),
    )[file_type]

    output_file = tmp_path / f"{file_type}.xlsx"
    result = CORPUS_CLEANERS[file_type](
        input_path=FIXTURES_DIR / f"{file_type}-corpus.csv",
        output_path=output_file,
    )

    assert result.success is True
    # Read every cell as text so numeric-looking strings are not coerced, then
    # normalize blanks to "" to match the web cleaner's empty-string cells.
    df = pd.read_excel(output_file, dtype=str).fillna("")
    assert df.to_dict(orient="records") == expected
