/* LinkedIn Analyzer - Analytics text normalization and topic extraction */

const STOP_WORDS = new Set([
    "the",
    "a",
    "an",
    "and",
    "or",
    "but",
    "in",
    "on",
    "at",
    "to",
    "for",
    "of",
    "with",
    "by",
    "from",
    "up",
    "about",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "between",
    "under",
    "again",
    "further",
    "then",
    "once",
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "all",
    "each",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "nor",
    "not",
    "only",
    "own",
    "same",
    "so",
    "than",
    "too",
    "very",
    "s",
    "t",
    "can",
    "will",
    "just",
    "don",
    "should",
    "now",
    "i",
    "you",
    "he",
    "she",
    "it",
    "we",
    "they",
    "what",
    "which",
    "who",
    "this",
    "that",
    "these",
    "those",
    "am",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "having",
    "do",
    "does",
    "did",
    "doing",
    "would",
    "could",
    "ought",
    "im",
    "youre",
    "hes",
    "shes",
    "its",
    "were",
    "theyre",
    "ive",
    "youve",
    "weve",
    "theyve",
    "id",
    "youd",
    "hed",
    "shed",
    "wed",
    "theyd",
    "ill",
    "youll",
    "hell",
    "shell",
    "well",
    "theyll",
    "isnt",
    "arent",
    "wasnt",
    "werent",
    "hasnt",
    "havent",
    "hadnt",
    "doesnt",
    "dont",
    "didnt",
    "wont",
    "wouldnt",
    "couldnt",
    "shouldnt",
    "my",
    "your",
    "his",
    "her",
    "our",
    "their",
    "me",
    "him",
    "us",
    "them",
    "if",
    "because",
    "as",
    "until",
    "while",
    "also",
    "even",
    "much",
    "many",
    "get",
    "got",
    "like",
    "know",
    "think",
    "make",
    "see",
    "one",
    "two",
    "new",
    "want",
    "way",
    "use",
    "go",
    "going",
    "come",
    "take",
    "really",
    "thing",
    "things",
    "something",
    "say",
    "said",
    "people",
    "time",
    "year",
    "years",
    "day",
    "days",
    "good",
    "first",
    "ve",
    "re",
    "ll",
    "d",
    "m",
    "let",
    "need",
    "back",
    "still",
    "every",
    "look",
    "www",
    "https",
    "http",
    "com",
    "linkedin",
    "amp",
    "hi",
    "hello",
]);

/**
 * Strip URLs and normalize whitespace in a text string.
 * @param {string} text - Raw text to normalize.
 * @returns {string} Cleaned text with URLs removed and whitespace collapsed.
 */
function normalizeText(text) {
    if (!text) {
        return "";
    }
    return String(text)
        .replace(/https?:\/\/\S+/gi, " ")
        .replace(/\s+/g, " ")
        .trim();
}

/**
 * Extract hashtags and significant words from text, filtering out stop words.
 * @param {string} text - Raw text to extract topics from.
 * @returns {string[]} Array of unique lowercase topic tokens.
 */
export function extractTopics(text) {
    const normalized = normalizeText(text);
    if (!normalized) {
        return [];
    }
    const hashtags = normalized.match(/#([A-Za-z0-9_]+)/g) || [];
    const textWithoutTags = normalized.replace(/#[A-Za-z0-9_]+/g, " ");
    const words = textWithoutTags.match(/\b[a-zA-Z]{3,}\b/g) || [];
    const tokenSet = new Set();
    hashtags.forEach((tag) => {
        const cleaned = tag.replace("#", "").toLowerCase();
        if (cleaned && !STOP_WORDS.has(cleaned)) {
            tokenSet.add(cleaned);
        }
    });
    words.forEach((word) => {
        const cleaned = word.toLowerCase();
        if (!STOP_WORDS.has(cleaned)) {
            tokenSet.add(cleaned);
        }
    });
    return Array.from(tokenSet);
}
